# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
jobs:
  build:
    docker:
      - image: circleci/node:8.1.0
    working_directory: ~/ExampleCI
    steps:
      - run:
          name: create container devops
          command: docker build -t devops .

  test:
    docker:
      - image: circleci/node:8.1.0
    steps:
      - run:
          name: test containers
          command: docker run devops npm test

  deploy-qa:
    docker:
      - image: circleci/node:8.1.0
    steps:
      - run:
          name: deploy to NOW
          command:  sh deployment/one.sh

  deploy-prod:
    docker:
      - image: circleci/node:8.1.0
    steps:
      - run:
          name: deploy to prod
          command: sh deployment/prod.sh

workflows:
  version: 2
  central_flow:
      jobs:
        - build
        - test:
            requires:
              - build
        - deploy-qa:
            requires:
              - build
            filters:
              branches:
                only: /feature_.*/
        - deploy-prod:
            requires:
              - build
            filters:
              branches:
                only: master