# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
jobs:
  build:
    docker:
      - image: circleci/node:8.1.0
    working_directory: ~/ExampleCI
    steps:
      - setup_remote_docker
      - checkout
      - run: docker build -t devops .
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run "tests"
      - run: docker run devops npm test

  deploy-qa:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/ExampleCI
    steps:
      - checkout
      - run:
          name: deploy to NOW
          command:  sh deployment/one.sh
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy-prod:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/ExampleCI
    steps:
      - checkout
      - run:
          name: deploy to prod
          command: sh deployment/prod.sh
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}



workflows:
  version: 2
  central_flow:
      jobs:
        - build
        - deploy-qa:
            requires:
              - build
            filters:
              branches:
                only: /feature_.*/
        - deploy-prod:
            requires:
              - build
            filters:
              branches:
                only: master